version: '3'

services:

  mongodb:
    image: mongo:6.0.3
    container_name: chat_service_db
    ports:
      - 27017:27017
    env_file: 
      - .env
    volumes:
      - chat-service-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  chat-service-data:
