version: '3'

services:
  chat_service:
    image: darkpearl/chat-service
    container_name: chat_service
    environment:
      - STRICTLY_CHECK_SOCKET=true
      - DATABASE_TYPE=mongo
      - DATABASE_URL=mongodb://root:password@mongodb:27017/chat_service_db
    ports:
      - 80:1337
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: chat_service_mongo
    ports:
      - 27017:27017
    env_file: 
      - .env
    volumes:
      - chat-service-db:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  chat-service-db:
