version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: chat_service_db
    ports:
      - 27017:27017
    env_file: 
      - .env
    volumes:
      - ./.data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
