version: '3'

services:
  chat_service:
    build: .
    container_name: chat_service
    environment:
      - DATABASE_TYPE=mongo
      - DATABASE_URL=mongodb://root:AbBE2smYVcsxGFUMUzOeQA@localhost:27017/chat_service_db
    ports:
      - 1337:1337
    links:
      - mongodb


  mongodb:
    image: mongo:latest
    container_name: chat_service_db
    ports:
      - 27017:27017
    environment: 
      - .env
    volumes:
      - chat-service-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  chat-service-data:
